//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGT_TFI.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeTexts() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIGT_TFI.Resources.HomeTexts", typeof(HomeTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acerca.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acciones.
        /// </summary>
        public static string Acciones {
            get {
                return ResourceManager.GetString("Acciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        public static string Agregar {
            get {
                return ResourceManager.GetString("Agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Recibos.
        /// </summary>
        public static string AgregarRecibos {
            get {
                return ResourceManager.GetString("AgregarRecibos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anular.
        /// </summary>
        public static string Anular {
            get {
                return ResourceManager.GetString("Anular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banco.
        /// </summary>
        public static string Banco {
            get {
                return ResourceManager.GetString("Banco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bitacora.
        /// </summary>
        public static string Bitacora {
            get {
                return ResourceManager.GetString("Bitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string Buscar {
            get {
                return ResourceManager.GetString("Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar por Nombre:.
        /// </summary>
        public static string BuscarPor {
            get {
                return ResourceManager.GetString("BuscarPor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Traslados.
        /// </summary>
        public static string BuscarTraslados {
            get {
                return ResourceManager.GetString("BuscarTraslados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cabecera.
        /// </summary>
        public static string Cabecera {
            get {
                return ResourceManager.GetString("Cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calle.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga.
        /// </summary>
        public static string Carga {
            get {
                return ResourceManager.GetString("Carga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Client.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cobranza.
        /// </summary>
        public static string Cobranza {
            get {
                return ResourceManager.GetString("Cobranza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo Postal.
        /// </summary>
        public static string CodigoPostal {
            get {
                return ResourceManager.GetString("CodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comision.
        /// </summary>
        public static string Comision {
            get {
                return ResourceManager.GetString("Comision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Computadora.
        /// </summary>
        public static string Computadora {
            get {
                return ResourceManager.GetString("Computadora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactenos.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encuentrenos.
        /// </summary>
        public static string Contacto2 {
            get {
                return ResourceManager.GetString("Contacto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contactos.
        /// </summary>
        public static string Contactos {
            get {
                return ResourceManager.GetString("Contactos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string Crear {
            get {
                return ResourceManager.GetString("Crear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cliente.
        /// </summary>
        public static string CrearCliente {
            get {
                return ResourceManager.GetString("CrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Cobranza.
        /// </summary>
        public static string CrearCobranza {
            get {
                return ResourceManager.GetString("CrearCobranza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Empresa.
        /// </summary>
        public static string CrearEmpresa {
            get {
                return ResourceManager.GetString("CrearEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Obra.
        /// </summary>
        public static string CrearObra {
            get {
                return ResourceManager.GetString("CrearObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuenta corriente.
        /// </summary>
        public static string CuentaCorriente {
            get {
                return ResourceManager.GetString("CuentaCorriente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuit.
        /// </summary>
        public static string Cuit {
            get {
                return ResourceManager.GetString("Cuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Depto.
        /// </summary>
        public static string Depto {
            get {
                return ResourceManager.GetString("Depto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        public static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directo.
        /// </summary>
        public static string Directo {
            get {
                return ResourceManager.GetString("Directo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento.
        /// </summary>
        public static string Documento {
            get {
                return ResourceManager.GetString("Documento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Domicilio.
        /// </summary>
        public static string Domicilio {
            get {
                return ResourceManager.GetString("Domicilio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Endosable.
        /// </summary>
        public static string Endosable {
            get {
                return ResourceManager.GetString("Endosable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Especialistas.
        /// </summary>
        public static string Especialistas {
            get {
                return ResourceManager.GetString("Especialistas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar a excel.
        /// </summary>
        public static string Exportar {
            get {
                return ResourceManager.GetString("Exportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas.
        /// </summary>
        public static string Facturas {
            get {
                return ResourceManager.GetString("Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Final.
        /// </summary>
        public static string FechafTraslado {
            get {
                return ResourceManager.GetString("FechafTraslado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Inicial.
        /// </summary>
        public static string FechaiTraslado {
            get {
                return ResourceManager.GetString("FechaiTraslado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fin.
        /// </summary>
        public static string Fin {
            get {
                return ResourceManager.GetString("Fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gerencia.
        /// </summary>
        public static string Gerencia {
            get {
                return ResourceManager.GetString("Gerencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hola .
        /// </summary>
        public static string Hola {
            get {
                return ResourceManager.GetString("Hola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        public static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese email y password.
        /// </summary>
        public static string IngresarEmailPass {
            get {
                return ResourceManager.GetString("IngresarEmailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese los datos del domicilio a continuación.
        /// </summary>
        public static string Ingresedatosdom {
            get {
                return ResourceManager.GetString("Ingresedatosdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesion.
        /// </summary>
        public static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iva.
        /// </summary>
        public static string Iva {
            get {
                return ResourceManager.GetString("Iva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leer mas.
        /// </summary>
        public static string Leermas {
            get {
                return ResourceManager.GetString("Leermas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Letra.
        /// </summary>
        public static string Letra {
            get {
                return ResourceManager.GetString("Letra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Clientes.
        /// </summary>
        public static string ListadoClientes {
            get {
                return ResourceManager.GetString("ListadoClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado Obras.
        /// </summary>
        public static string ListadoObras {
            get {
                return ResourceManager.GetString("ListadoObras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listar.
        /// </summary>
        public static string Listar {
            get {
                return ResourceManager.GetString("Listar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de recorridos por obra.
        /// </summary>
        public static string listrecorridosporobra {
            get {
                return ResourceManager.GetString("listrecorridosporobra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listado de Transportes.
        /// </summary>
        public static string listtranspor {
            get {
                return ResourceManager.GetString("listtranspor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localizar.
        /// </summary>
        public static string Localizar {
            get {
                return ResourceManager.GetString("Localizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marca.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Medio.
        /// </summary>
        public static string Medio {
            get {
                return ResourceManager.GetString("Medio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        public static string Mensaje {
            get {
                return ResourceManager.GetString("Mensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mision.
        /// </summary>
        public static string Mision {
            get {
                return ResourceManager.GetString("Mision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brindar y garantizar un servicio de transporte seguro y de excelencia reconocida por los clientes, basado en un sistema de gestión y control de flota de vanguardia en el servicio de transporte..
        /// </summary>
        public static string MisionTxt {
            get {
                return ResourceManager.GetString("MisionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modelo.
        /// </summary>
        public static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monto.
        /// </summary>
        public static string Monto {
            get {
                return ResourceManager.GetString("Monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NombreFantasia.
        /// </summary>
        public static string Nombrefantasia {
            get {
                return ResourceManager.GetString("Nombrefantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Cliente.
        /// </summary>
        public static string NuevoCliente {
            get {
                return ResourceManager.GetString("NuevoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Contacto.
        /// </summary>
        public static string NuevoContacto {
            get {
                return ResourceManager.GetString("NuevoContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a N° Cheque.
        /// </summary>
        public static string NumeroCheque {
            get {
                return ResourceManager.GetString("NumeroCheque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objetivos.
        /// </summary>
        public static string Objetivos {
            get {
                return ResourceManager.GetString("Objetivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser líderes y reconocidos en el mercado como una empresa de transporte tierras..
        /// </summary>
        public static string ObjetivosText {
            get {
                return ResourceManager.GetString("ObjetivosText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obra.
        /// </summary>
        public static string Obra {
            get {
                return ResourceManager.GetString("Obra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ha olvidado su contraseña?.
        /// </summary>
        public static string Olvidado {
            get {
                return ResourceManager.GetString("Olvidado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patente.
        /// </summary>
        public static string Patente {
            get {
                return ResourceManager.GetString("Patente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Piso.
        /// </summary>
        public static string Piso {
            get {
                return ResourceManager.GetString("Piso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Plazo.
        /// </summary>
        public static string Plazo {
            get {
                return ResourceManager.GetString("Plazo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio.
        /// </summary>
        public static string Precio {
            get {
                return ResourceManager.GetString("Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        public static string Proveedores {
            get {
                return ResourceManager.GetString("Proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provincia.
        /// </summary>
        public static string Provincia {
            get {
                return ResourceManager.GetString("Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razon Social.
        /// </summary>
        public static string RazonSocial {
            get {
                return ResourceManager.GetString("RazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recordarme?.
        /// </summary>
        public static string Recordar {
            get {
                return ResourceManager.GetString("Recordar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recorrido.
        /// </summary>
        public static string Recorrido {
            get {
                return ResourceManager.GetString("Recorrido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recorridos.
        /// </summary>
        public static string Recorridos {
            get {
                return ResourceManager.GetString("Recorridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string Registrar {
            get {
                return ResourceManager.GetString("Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar como nuevo usuario.
        /// </summary>
        public static string Registrarse {
            get {
                return ResourceManager.GetString("Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablecer.
        /// </summary>
        public static string Restablecer {
            get {
                return ResourceManager.GetString("Restablecer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restablezca la contraseña.
        /// </summary>
        public static string RestablecerPass {
            get {
                return ResourceManager.GetString("RestablecerPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saldo Inicial.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        public static string Seleccionar {
            get {
                return ResourceManager.GetString("Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema.
        /// </summary>
        public static string Sistema {
            get {
                return ResourceManager.GetString("Sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Soporte.
        /// </summary>
        public static string Soporte {
            get {
                return ResourceManager.GetString("Soporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SubTotal.
        /// </summary>
        public static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tara.
        /// </summary>
        public static string Tara {
            get {
                return ResourceManager.GetString("Tara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        public static string Tipo {
            get {
                return ResourceManager.GetString("Tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Contribuyente.
        /// </summary>
        public static string TipoContribuyente {
            get {
                return ResourceManager.GetString("TipoContribuyente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titular.
        /// </summary>
        public static string Titular {
            get {
                return ResourceManager.GetString("Titular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿QUE ES LO QUE HACEMOS?.
        /// </summary>
        public static string Titulo1 {
            get {
                return ResourceManager.GetString("Titulo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manejamos de forma correcta sus recursos.
        /// </summary>
        public static string Titulo2 {
            get {
                return ResourceManager.GetString("Titulo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transporte.
        /// </summary>
        public static string Transporte {
            get {
                return ResourceManager.GetString("Transporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser líderes y reconocidos en el mercado como una empresa de transporte tierras..
        /// </summary>
        public static string TransporteText {
            get {
                return ResourceManager.GetString("TransporteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Traslado.
        /// </summary>
        public static string Traslado {
            get {
                return ResourceManager.GetString("Traslado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UsuarioWindows.
        /// </summary>
        public static string UsuarioWindows {
            get {
                return ResourceManager.GetString("UsuarioWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta.
        /// </summary>
        public static string Venta {
            get {
                return ResourceManager.GetString("Venta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventas.
        /// </summary>
        public static string Ventas {
            get {
                return ResourceManager.GetString("Ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ser líderes y reconocidos en el mercado como una empresa de transporte tierras..
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        public static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
